# Chapter 03. 데이터 수집하기

In [29]:
import requests
import bs4

naver_url = "https://www.naver.com"
naver_response = requests.get(naver_url)
# naver_response.text

In [30]:
import bs4

naver_bs = bs4.BeautifulSoup(naver_response.text, 'lxml')
naver_bs.find('span', class_='ah_k')
# find는 같은 class 속성들이 있다면 그중에 맨 첫 번째 것만 가져옴.
# 만약 class 속성을 지정해주지 않는다면 이 페이지에 있는 모든 span 태그 중 첫번쨰 코드를 가져옴

In [31]:
result = naver_bs.find('span')
result.text

'뉴스스탠드 바로가기'

In [32]:
naver_bs.find_all('span')

[<span>뉴스스탠드 바로가기</span>,
 <span>주제별캐스트 바로가기</span>,
 <span>타임스퀘어 바로가기</span>,
 <span>쇼핑캐스트 바로가기</span>,
 <span>로그인 바로가기</span>,
 <span>옆에서 쓰-윽 꺼내보는 재미! </span>,
 <span>다운로드</span>,
 <span class="blind">NAVER whale</span>,
 <span class="blind">네이버</span>,
 <span class="blind">쥬니어네이버</span>,
 <span class="blind">해피빈</span>,
 <span class="blind">검색</span>,
 <span class="ico_search_submit"></span>,
 <span class="ico_keyboard"></span>,
 <span class="blind">입력도구</span>,
 <span class="blind _text">자동완성/최근검색어 펼치기</span>,
 <span class="ico_arr"></span>,
 <span class="desc">
 <span class="plus_txt _plusTxt">시간대와 관심사에 맞춘 <em class="txt">컨텍스트 자동완성</em></span>
 <a class="spat ico_info _plusHelp" href="https://help.naver.com/support/contents/contents.nhn?serviceNo=606&amp;categoryNo=16658" onclick="__atcmpCR(event, this, 'plus.help', '','','');" target="_blank"><span class="blind">도움말 보기</span></a>
 </span>,
 <span class="plus_txt _plusTxt">시간대와 관심사에 맞춘 <em class="txt">컨텍스트 자동완성</em></span>,
 <span class="blind">도움말 보기</span>,
 <span class="switch _plus_btn">
 <a class="btn_turnon active" href="#" onclick="__atcmpCR(event, this, 'plus.use', '','','');">ON<span class="blind">선택됨</span></a>
 <a class="btn_turnoff" href="#" onclick="__atcmpCR(event, this, 'plus.unuse', '','','');">OFF</a>
 </span>,
 <span class="blind">선택됨</span>,
 <span class="fl"><a class="_help" href="https://help.naver.com/support/service/main.nhn?serviceNo=606&amp;categoryNo=1987" onclick="__atcmpCR(event, this, 'help', '','','');" target="_blank">도움말</a><span class="atcmp_bar"></span><a class="report" href="https://help.naver.com/support/contents/contents.nhn?serviceNo=605&amp;categoryNo=18215" onclick="__atcmpCR(event, this, 'report', '','','');" target="_blank">신고</a></span>,
 <span class="atcmp_bar"></span>,
 <span><em><a class="hisoff" href="javascript:;">검색어저장 켜기</a><span class="atcmp_bar"></span></em><a class="funoff" href="javascript:;">자동완성 끄기</a></span>,
 <span class="atcmp_bar"></span>,
 <span class="atcmp_helper _help_tooltip1">기능을 다시 켤 때는 <em class="ico_search spat">자동완성 펼치기</em>을 클릭하세요</span>,
 <span class="fl"><a class="_help" href="https://help.naver.com/support/service/main.nhn?serviceNo=606&amp;categoryNo=1987" onclick="__atcmpCR(event, this, 'help', '','','');" target="_blank">도움말</a><span class="atcmp_bar"></span><a class="report" href="https://help.naver.com/support/contents/contents.nhn?serviceNo=605&amp;categoryNo=18215" onclick="__atcmpCR(event, this, 'report', '','','');" target="_blank">신고</a></span>,
 <span class="atcmp_bar"></span>,
 <span><em><a class="hisoff" href="javascript:;">검색어저장 켜기</a><span class="atcmp_bar"></span></em><a class="funoff" href="javascript:;">자동완성 끄기</a></span>,
 <span class="atcmp_bar"></span>,
 <span class="atcmp_helper _help_tooltip2">기능을 다시 켤 때는 <em class="ico_search spat">자동완성 펼치기</em>을 클릭하세요</span>,
 <span class="fl"><a class="_help" href="https://help.naver.com/support/service/main.nhn?serviceNo=606&amp;categoryNo=1987" onclick="__atcmpCR(event, this, 'help', '','','');" target="_blank">도움말</a><span class="atcmp_bar"></span><a class="report" href="https://help.naver.com/support/contents/contents.nhn?serviceNo=605&amp;categoryNo=18215" onclick="__atcmpCR(event, this, 'report', '','','');" target="_blank">신고</a></span>,
 <span class="atcmp_bar"></span>,
 <span><em><a class="hisoff" href="javascript:;">검색어저장 켜기</a><span class="atcmp_bar"></span></em><a class="funoff" href="javascript:;">자동완성 끄기</a></span>,
 <span class="atcmp_bar"></span>,
 <span class="atcmp_helper _help_tooltip3">기능을 다시 켤 때는 <em class="ico_search spat">자동완성 펼치기</em>을 클릭하세요</span>,
 <span class="fl"><a class="_help" href="https://help.naver.com/support/service/main.nhn?serviceNo=606&amp;categoryNo=1987" onclick="__atcmpCR(event, this, 'help', '','','');" target="_blank">도움말</a><span class="atcmp_bar"></span><a class="report" href="https://help.naver.com/support/contents/contents.nhn?serviceNo=605&amp;categoryNo=18215" onclick="__atcmpCR(event, this, 'report', '','','');" target="_blank">신고</a></span>,
 <span class="atcmp_bar"></span>,
 <span><em><a class="hisoff" href="javascript:;">검색어저장 켜기</a><span class="atcmp_bar"></span></em><a class="funoff" href="javascript:;">자동완성 켜기</a></span>,
 <span class="atcmp_bar"></span>,
 <span style="display:none">@in_txt@</span>,
 <span class="star spat">내 검색어 등록</span>,
 <span class="blind">알림</span>,
 <span class="blind">알림</span>,
 <span class="fl"><a class="_delMode" href="javascript:;">기록 삭제</a></span>,
 <span><a class="_keywordOff" href="javascript:;">검색어저장 끄기</a><span class="atcmp_bar"></span><a class="_acOff" href="javascript:;">자동완성 끄기</a></span>,
 <span class="atcmp_bar"></span>,
 <span class="fl"><a class="_delAll" href="javascript:;" title="최근 검색어 기록을 모두 삭제합니다.">기록 전체 삭제</a></span>,
 <span><a class="_delDone" href="javascript:;">완료</a></span>,
 <span class="fl"><a class="_delAll" href="javascript:;" title="설정된 내 검색어를 모두 삭제합니다.">기록 전체 삭제</a></span>,
 <span><a class="_keywordOff" href="javascript:;">검색어저장 끄기</a><span class="atcmp_bar"></span><a class="_acOff" href="javascript:;">자동완성 끄기</a></span>,
 <span class="atcmp_bar"></span>,
 <span class="atcmp_helper _help2">기능을 다시 켤 때는 <em class="ico_search spat">자동완성 펼치기</em>을 클릭하세요</span>,
 <span class="mask"></span>,
 <span class="ico_alert spat"></span>,
 <span class="ico_alert spat"></span>,
 <span class="_passage"></span>,
 <span class="term"><span class="_term"></span><a class="link _link" href="#" onclick="window.nclick(this,'sug.vote','','',event);" target="_blank">자세히보기</a></span>,
 <span class="_term"></span>,
 <span class="veta_bd_t"></span>,
 <span class="veta_bd_b"></span>,
 <span class="veta_bd_l"></span>,
 <span class="veta_bd_r"></span>,
 <span class="blind">리스트형</span>,
 <span class="blind">썸네일형</span>,
 <span class="blind">설정</span>,
 <span class="blind">이전</span>,
 <span class="blind">다음</span>,
 <span class="blind">닫기</span>,
 <span class="blind">닫기</span>,
 <span class="blind">이전</span>,
 <span class="blind">다음</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_dim"></span>,
 <span class="blind">닫기</span>,
 <span class="blind">닫기</span>,
 <span class="blind">이전</span>,
 <span class="blind">다음</span>,
 <span class="blind">다음</span>,
 <span class="blind">닫기</span>,
 <span class="blind">닫기</span>,
 <span class="blind">이전</span>,
 <span class="blind">다음</span>,
 <span class="blind">닫기</span>,
 <span class="blind">닫기</span>,
 <span class="dsc">주제별로 분류된 다양한 글 모음</span>,
 <span class="info"><strong class="new">2,144</strong> 개의 글</span>,
 <span class="blind">이전</span>,
 <span class="blind">다음</span>,
 <span class="thumb_bd"></span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="source"><span class="source_inner">리얼푸드</span></span>,
 <span class="source_inner">리얼푸드</span>,
 <span class="thumb_bd"></span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">4일 전</span>,
 <span class="source"><span class="source_inner">전성기</span></span>,
 <span class="source_inner">전성기</span>,
 <span class="thumb_bd"></span>,
 <span class="date">6일 전</span>,
 <span class="source"><span class="source_inner">리얼푸드 Realfoods</span></span>,
 <span class="source_inner">리얼푸드 Realfoods</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">제이</span></span>,
 <span class="source_inner">제이</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">서울대학교병원</span></span>,
 <span class="source_inner">서울대학교병원</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">04:37</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">5일 전</span>,
 <span class="source"><span class="source_inner">네이버FARM TV</span></span>,
 <span class="source_inner">네이버FARM TV</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">05:38</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">5일 전</span>,
 <span class="source"><span class="source_inner">경상북도TV</span></span>,
 <span class="source_inner">경상북도TV</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">05:30</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">5일 전</span>,
 <span class="source"><span class="source_inner">네이버FARM TV</span></span>,
 <span class="source_inner">네이버FARM TV</span>,
 <span class="thumb_bd"></span>,
 <span class="date">7개월 전</span>,
 <span class="source"><span class="source_inner">데일리</span></span>,
 <span class="source_inner">데일리</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">5일 전</span>,
 <span class="source"><span class="source_inner">입질의 추억</span></span>,
 <span class="source_inner">입질의 추억</span>,
 <span class="thumb_bd"></span>,
 <span class="date">4일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">02:54</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">2주일 전</span>,
 <span class="source"><span class="source_inner">NBS 한국농업방송 공식채널</span></span>,
 <span class="source_inner">NBS 한국농업방송 공식채널</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">01:20</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">NBS 한국농업방송 공식채널</span></span>,
 <span class="source_inner">NBS 한국농업방송 공식채널</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">07:22</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">2주일 전</span>,
 <span class="source"><span class="source_inner">경상북도TV</span></span>,
 <span class="source_inner">경상북도TV</span>,
 <span class="thumb_bd"></span>,
 <span class="date">2일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">잡컴퍼니</span></span>,
 <span class="source_inner">잡컴퍼니</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">트렌드DA</span></span>,
 <span class="source_inner">트렌드DA</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">06:56</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">네이버FARM TV</span></span>,
 <span class="source_inner">네이버FARM TV</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">04:30</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">2주일 전</span>,
 <span class="source"><span class="source_inner">경상북도TV</span></span>,
 <span class="source_inner">경상북도TV</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">07:17</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">2주일 전</span>,
 <span class="source"><span class="source_inner">지나철</span></span>,
 <span class="source_inner">지나철</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">작은가게오래가게</span></span>,
 <span class="source_inner">작은가게오래가게</span>,
 <span class="thumb_bd"></span>,
 <span class="date">3일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1년 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">그린매거진</span></span>,
 <span class="source_inner">그린매거진</span>,
 <span class="thumb_bd"></span>,
 <span class="date">3개월 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">03:32</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">2주일 전</span>,
 <span class="source"><span class="source_inner">NBS 한국농업방송 공식채널</span></span>,
 <span class="source_inner">NBS 한국농업방송 공식채널</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">05:31</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">4주일 전</span>,
 <span class="source"><span class="source_inner">서울시50플러스재단</span></span>,
 <span class="source_inner">서울시50플러스재단</span>,
 <span class="thumb_dim"></span>,
 <span class="thumb_bd"></span>,
 <span class="blind">재생</span>,
 <span class="theme_runtime"><span class="runtime_bg">재생시간</span><em class="time">03:38</em></span>,
 <span class="runtime_bg">재생시간</span>,
 <span class="date">2주일 전</span>,
 <span class="source"><span class="source_inner">네이버FARM TV</span></span>,
 <span class="source_inner">네이버FARM TV</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">데일리</span></span>,
 <span class="source_inner">데일리</span>,
 <span class="thumb_bd"></span>,
 <span class="date">3일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1년 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1개월 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">마이sun원현민</span></span>,
 <span class="source_inner">마이sun원현민</span>,
 <span class="thumb_bd"></span>,
 <span class="date">4일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">아리쭈</span></span>,
 <span class="source_inner">아리쭈</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">이슈잇슈</span></span>,
 <span class="source_inner">이슈잇슈</span>,
 <span class="thumb_bd"></span>,
 <span class="date">4일 전</span>,
 <span class="source"><span class="source_inner">광주광역시농기센터</span></span>,
 <span class="source_inner">광주광역시농기센터</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">퀘럼</span></span>,
 <span class="source_inner">퀘럼</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">국민건강보험공단</span></span>,
 <span class="source_inner">국민건강보험공단</span>,
 <span class="thumb_bd"></span>,
 <span class="date">6일 전</span>,
 <span class="source"><span class="source_inner">트리플래닛</span></span>,
 <span class="source_inner">트리플래닛</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">식약지킴이</span></span>,
 <span class="source_inner">식약지킴이</span>,
 <span class="thumb_bd"></span>,
 <span class="date">6개월 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">소믈리에타임즈</span></span>,
 <span class="source_inner">소믈리에타임즈</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">전원주택라이프</span></span>,
 <span class="source_inner">전원주택라이프</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1개월 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">야미가든</span></span>,
 <span class="source_inner">야미가든</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1개월 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">3일 전</span>,
 <span class="source"><span class="source_inner">여행에미치다</span></span>,
 <span class="source_inner">여행에미치다</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">한국영농신문</span></span>,
 <span class="source_inner">한국영농신문</span>,
 <span class="thumb_bd"></span>,
 <span class="date">1주일 전</span>,
 <span class="source"><span class="source_inner">더농부</span></span>,
 <span class="source_inner">더농부</span>,
 <span class="thumb_bd"></span>,
 <span class="date">4일 전</span>,
 <span class="source"><span class="source_inner">완주군청</span></span>,
 <span class="source_inner">완주군청</span>,
 <span class="thumb_bd"></span>,

In [33]:
result_list = naver_bs.find_all('span')
for span in result_list:
    print(span.text)

뉴스스탠드 바로가기
주제별캐스트 바로가기
타임스퀘어 바로가기
쇼핑캐스트 바로가기
로그인 바로가기
옆에서 쓰-윽 꺼내보는 재미!
다운로드
NAVER whale
네이버
쥬니어네이버
해피빈
검색


입력도구
자동완성/최근검색어 펼치기


시간대와 관심사에 맞춘 컨텍스트 자동완성
도움말 보기

시간대와 관심사에 맞춘 컨텍스트 자동완성
도움말 보기

ON선택됨
OFF

선택됨
도움말신고

검색어저장 켜기자동완성 끄기

기능을 다시 켤 때는 자동완성 펼치기을 클릭하세요
도움말신고

검색어저장 켜기자동완성 끄기

기능을 다시 켤 때는 자동완성 펼치기을 클릭하세요
도움말신고

검색어저장 켜기자동완성 끄기

기능을 다시 켤 때는 자동완성 펼치기을 클릭하세요
도움말신고

검색어저장 켜기자동완성 켜기

@in_txt@
내 검색어 등록
알림
알림
기록 삭제
검색어저장 끄기자동완성 끄기

기록 전체 삭제
완료
기록 전체 삭제
검색어저장 끄기자동완성 끄기

기능을 다시 켤 때는 자동완성 펼치기을 클릭하세요




자세히보기





리스트형
썸네일형
설정
이전
다음
닫기
닫기
이전
다음
























닫기
닫기
이전
다음
다음
닫기
닫기
이전
다음
닫기
닫기
주제별로 분류된 다양한 글 모음
2,144 개의 글
이전
다음

더농부
더농부

리얼푸드
리얼푸드

더농부
더농부

더농부
더농부

4일 전
전성기
전성기

6일 전
리얼푸드 Realfoods
리얼푸드 Realfoods

1주일 전
제이
제이

1주일 전
서울대학교병원
서울대학교병원


재생
재생시간04:37
재생시간
5일 전
네이버FARM TV
네이버FARM TV


재생
재생시간05:38
재생시간
5일 전
경상북도TV
경상북도TV


재생
재생시간05:30
재생시간
5일 전
네이버FARM TV
네이버FARM TV

7개월 전
데일리
데일리

1주일 전
더농부
더농부

5일 전
입질의 추억
입질의 추억

4일 전
더농부
더농부


재생
재생시간02:54
재생시간
2주일 전
NBS 한국농업방송 공식채널
NBS 한국농업방송 공식채널


재생
재생시간01:20
재생시간
1주일 전
NBS 한국농업방송 공식채널
NBS 한국농업방송 공식채널


재생
재생시간07:22
재생시간
2주일 전
경상북도TV
경상북도TV

2일 전
더농부
더농부

1주일 전
더농부
더농부

1주일 전
잡컴퍼니
잡컴퍼니

1주일 전
더농부
더농부

1주일 전
트렌드DA
트렌드DA


재생
재생시간06:56
재생시간
1주일 전
네이버FARM TV
네이버FARM TV


재생
재생시간04:30
재생시간
2주일 전
경상북도TV
경상북도TV


재생
재생시간07:17
재생시간
2주일 전
지나철
지나철

1주일 전
작은가게오래가게
작은가게오래가게

3일 전
더농부
더농부

1년 전
더농부
더농부

1주일 전
그린매거진
그린매거진

3개월 전
더농부
더농부


재생
재생시간03:32
재생시간
2주일 전
NBS 한국농업방송 공식채널
NBS 한국농업방송 공식채널


재생
재생시간05:31
재생시간
4주일 전
서울시50플러스재단
서울시50플러스재단


재생
재생시간03:38
재생시간
2주일 전
네이버FARM TV
네이버FARM TV

1주일 전
데일리
데일리

3일 전
더농부
더농부

1년 전
더농부
더농부

1개월 전
더농부
더농부

1주일 전
마이sun원현민
마이sun원현민

4일 전
더농부
더농부

1주일 전
아리쭈
아리쭈

1주일 전
이슈잇슈
이슈잇슈

4일 전
광주광역시농기센터
광주광역시농기센터

1주일 전
퀘럼
퀘럼

1주일 전
국민건강보험공단
국민건강보험공단

6일 전
트리플래닛
트리플래닛

1주일 전
식약지킴이
식약지킴이

6개월 전
더농부
더농부

1주일 전
소믈리에타임즈
소믈리에타임즈

1주일 전
전원주택라이프
전원주택라이프

1개월 전
더농부
더농부

1주일 전
야미가든
야미가든

1개월 전
더농부
더농부

3일 전
여행에미치다
여행에미치다

1주일 전
한국영농신문
한국영농신문

1주일 전
더농부
더농부

4일 전
완주군청
완주군청

4일 전
더농부
더농부

3일 전
더농부
더농부

3일 전
더농부
더농부

1주일 전
농촌진흥청
농촌진흥청

1주일 전
미소곡간
미소곡간

1주일 전
소혹성
소혹성

5일 전
대한민국 구석구석
대한민국 구석구석

5일 전
농촌여행 웰촌
농촌여행 웰촌

1주일 전
강원도
강원도

1주일 전
브라보마이라이프
브라보마이라이프

5개월 전
더농부
더농부

1주일 전
더농부
더농부

4일 전
더농부
더농부

1주일 전
소혹성
소혹성

1주일 전
월간 전원속의 내집
월간 전원속의 내집

5일 전
강원여행
강원여행

3일 전
더농부
더농부
NAVER
이전
다음
저녁방송 메인뉴스 보기
코로나바이러스감염증19 현황
28.0°
20.0°
마곡동
마곡동




TOP
라이트 모드로 보기

## 3.3 재무 데이터 구해 오기

In [34]:
import pandas as pd

fs_url = 'http://comp.fnguide.com/SVO2/asp/SVD_Finance.asp?pGB=1&gicode=A005930&cID=&MenuYn=Y&ReportGB=&NewMenuID=103&stkGb=701'
fs_page = requests.get(fs_url)
fs_tables = pd.read_html(fs_page.text) # 연간, 분기 2개씩 나옴. 포괄손익, 재무제표, 현금흐름 = 6개

In [35]:
fs_tables[0]

,IFRS(연결),2017/12,2018/12,2019/12,2020/03,전년동기,전년동기(%)
0,매출액,2395754.0,2437714.0,2304009.0,553252.0,523855.0,5.6
1,매출원가,1292907.0,1323944.0,1472395.0,348067.0,327465.0,6.3
2,매출총이익,1102847.0,1113770.0,831613.0,205185.0,196391.0,4.5
3,판매비와관리비계산에 참여한 계정 펼치기,566397.0,524903.0,553928.0,140711.0,134058.0,5.0
4,영업이익,536450.0,588867.0,277685.0,64473.0,62333.0,3.4
5,영업이익(발표기준),536450.0,588867.0,277685.0,64473.0,62333.0,3.4
6,금융수익계산에 참여한 계정 펼치기,97374.0,99993.0,101616.0,37914.0,19165.0,97.8
7,금융원가계산에 참여한 계정 펼치기,89789.0,86089.0,82749.0,34940.0,13792.0,153.3
8,기타수익계산에 참여한 계정 펼치기,30107.0,14850.0,17787.0,3155.0,3218.0,-2.0
9,기타비용계산에 참여한 계정 펼치기,14196.0,11420.0,14147.0,3641.0,2571.0,41.6
10,"종속기업,공동지배기업및관계기업관련손익계산에 참여한 계정 펼치기",2014.0,5398.0,4130.0,606.0,777.0,-21.9
11,세전계속사업이익,561960.0,611600.0,304322.0,67569.0,69130.0,-2.3
12,법인세비용,140092.0,168151.0,86933.0,18719.0,18694.0,0.1
13,계속영업이익,421867.0,443449.0,217389.0,48849.0,50436.0,-3.1
14,중단영업이익,NaN,NaN,NaN,NaN,NaN,NaN
15,당기순이익,421867.0,443449.0,217389.0,48849.0,50436.0,-3.1
16,지배주주순이익,413446.0,438909.0,215051.0,48896.0,51075.0,-4.3
17,비지배주주순이익,8422.0,4540.0,2338.0,-47.0,-639.0,적자지속

In [36]:
# 포괄손익계산서
temp_df = fs_tables[0]
temp_df = temp_df.set_index('IFRS(연결)')
temp_df = temp_df[['2017/12', '2018/12', '2019/12', '2020/03']]
temp_df

                                      2017/12    2018/12    2019/12   2020/03
IFRS(연결)
매출액                                 2395754.0  2437714.0  2304009.0  553252.0
매출원가                                1292907.0  1323944.0  1472395.0  348067.0
매출총이익                               1102847.0  1113770.0   831613.0  205185.0
판매비와관리비계산에 참여한 계정 펼치기                566397.0   524903.0   553928.0  140711.0
영업이익                                 536450.0   588867.0   277685.0   64473.0
영업이익(발표기준)                           536450.0   588867.0   277685.0   64473.0
금융수익계산에 참여한 계정 펼치기                    97374.0    99993.0   101616.0   37914.0
금융원가계산에 참여한 계정 펼치기                    89789.0    86089.0    82749.0   34940.0
기타수익계산에 참여한 계정 펼치기                    30107.0    14850.0    17787.0    3155.0
기타비용계산에 참여한 계정 펼치기                    14196.0    11420.0    14147.0    3641.0
종속기업,공동지배기업및관계기업관련손익계산에 참여한 계정 펼치기     2014.0     5398.0     4130.0     606.0
세전계속사업이익                             561960.0   611600.0   304322.0   67569.0
법인세비용                                140092.0   168151.0    86933.0   18719.0
계속영업이익                               421867.0   443449.0   217389.0   48849.0
중단영업이익                                    NaN        NaN        NaN       NaN
당기순이익                                421867.0   443449.0   217389.0   48849.0
지배주주순이익                              413446.0   438909.0   215051.0   48896.0
비지배주주순이익                               8422.0     4540.0     2338.0     -47.0

In [37]:
# 사용할 행들만 선택
temp_df = temp_df.loc[['매출액', '영업이익', '당기순이익']]
temp_df

            2017/12    2018/12    2019/12   2020/03
IFRS(연결)
매출액       2395754.0  2437714.0  2304009.0  553252.0
영업이익       536450.0   588867.0   277685.0   64473.0
당기순이익      421867.0   443449.0   217389.0   48849.0

In [38]:
# 재무상태표와 현금흐름표
temp_df2 = fs_tables[2]
temp_df2 = temp_df2.set_index('IFRS(연결)')
temp_df2 = temp_df2.loc[['자산', '부채', '자본']]

temp_df3 = fs_tables[4]
temp_df3 = temp_df3.set_index('IFRS(연결)')
temp_df3 = temp_df3.loc[['영업활동으로인한현금흐름']]

In [39]:
fs_df = pd.concat([temp_df, temp_df2, temp_df3]) # 행을 위아래로 붙임
fs_df

                2017/12    2018/12    2019/12    2020/03
IFRS(연결)
매출액           2395754.0  2437714.0  2304009.0   553252.0
영업이익           536450.0   588867.0   277685.0    64473.0
당기순이익          421867.0   443449.0   217389.0    48849.0
자산            3017521.0  3393572.0  3525645.0  3574575.0
부채             872607.0   916041.0   896841.0   910698.0
자본            2144914.0  2477532.0  2628804.0  2663877.0
영업활동으로인한현금흐름   621620.0   670319.0   453829.0   118299.0

In [40]:
# 회사 코드가 들어가면 데이터프레임 생성하게 만듬
def make_fs_dataframe(firm_code):
    fs_url = 'https://comp.fnguide.com/SVO2/asp/SVD_Finance.asp?pGB=1&cID=&MenuYn=Y&ReportGB=D&NewMenuID=103&stkGb=701&gicode=' + firm_code
    fs_page = requests.get(fs_url)
    fs_tables = pd.read_html(fs_page.text)
    
    temp_df = fs_tables[0]
    temp_df = temp_df.set_index(temp_df.columns[0])
    temp_df = temp_df[temp_df.columns[:4]]
    temp_df = temp_df.loc[['매출액', '영업이익', '당기순이익']]

    temp_df2 = fs_tables[2]
    temp_df2 = temp_df2.set_index(temp_df2.columns[0])
    temp_df2 = temp_df2.loc[['자산', '부채', '자본']]

    temp_df3 = fs_tables[4]
    temp_df3 = temp_df3.set_index(temp_df3.columns[0])
    temp_df3 = temp_df3.loc[['영업활동으로인한현금흐름']]

    fs_df = pd.concat([temp_df, temp_df2, temp_df3])
    
    return fs_df

In [41]:
make_fs_dataframe('A005380') # 현대차 제무재표

                2017/12    2018/12    2019/12    2020/03
IFRS(연결)
매출액            963761.0   968126.0  1057464.0   253194.0
영업이익            45747.0    24222.0    36055.0     8638.0
당기순이익           45464.0    16450.0    31856.0     5527.0
자산            1781995.0  1806558.0  1945122.0  1988508.0
부채            1034421.0  1067597.0  1181465.0  1229242.0
자본             747574.0   738960.0   763658.0   759266.0
영업활동으로인한현금흐름    39224.0    37643.0     4198.0     8220.0

In [42]:
# 2000여 개의 회사코드를 인덱싱하여 같이 관리하는게 효율적이다.
# 형태 바꾸기

code = 'A005930'
fs_df = make_fs_dataframe(code)
temp_df = pd.DataFrame({code : fs_df['2017/12']})
temp_df = temp_df.T # 데이터프레임의 행과 열을 바꾸는 명령어
temp_df.columns = [['2017/12']*len(fs_df), temp_df.columns] # 이중 칼럼에서 위에 갈 칼럼을 앞에 넣고 미으로 갈 칼럼을 뒤에 넣는다.
temp_df

            2017/12                                                      \
IFRS(연결)        매출액      영업이익     당기순이익         자산        부채         자본
A005930   2395754.0  536450.0  421867.0  3017521.0  872607.0  2144914.0


IFRS(연결) 영업활동으로인한현금흐름
A005930      621620.0

In [43]:
def change_df(firm_code, dataframe):
    for num, col in enumerate(dataframe.columns):
        temp_df = pd.DataFrame({code : dataframe[col]})
        temp_df = temp_df.T
        temp_df.columns = [[col]*len(dataframe), temp_df.columns]
        if num == 0:
            total_df = temp_df
        else:
             total_df = pd.merge(total_df, temp_df, how='outer', left_index=True, right_index=True)
    return total_df

In [44]:
# 5개 회사 재무제포 데이터를 합쳐보기
firmcode_list = ['A005930', 'A005380', 'A035420', 'A003550', 'A034730']

for num, code in enumerate(firmcode_list):
    fs_df = make_fs_dataframe(code)
    fs_df_changed = change_df(code, fs_df)
    if num == 0:
        total_fs = fs_df_changed
    else:
        total_fs = pd.concat([total_fs, fs_df_changed])
total_fs

# 참고로 A005390 같은 기업의 연도는 2017/06 결산 연도가 다른건 데이터가 안나올 수 있음

            2017/12                                                       \
IFRS(연결)        매출액      영업이익     당기순이익         자산         부채         자본
A005930   2395754.0  536450.0  421867.0  3017521.0   872607.0  2144914.0
A005380    963761.0   45747.0   45464.0  1781995.0  1034421.0   747574.0
A035420     46785.0   11792.0    7701.0    80193.0    27141.0    53052.0
A003550    118411.0   21858.0   24356.0   216477.0    54682.0   161795.0
A034730    906128.0   57450.0   50665.0  1097835.0   640270.0   457564.0

                         2018/12                      ...    2019/12  \
IFRS(연결) 영업활동으로인한현금흐름        매출액      영업이익     당기순이익  ...         부채
A005930      621620.0  2437714.0  588867.0  443449.0  ...   896841.0
A005380       39224.0   968126.0   24222.0   16450.0  ...  1181465.0
A035420        9400.0    55869.0    9425.0    6279.0  ...    57956.0
A003550       10584.0    77434.0   18213.0   18829.0  ...    34136.0
A034730       69301.0  1001616.0   46838.0   61511.0  ...   798380.0

                                   2020/03                               \
IFRS(연결)         자본 영업활동으로인한현금흐름       매출액     영업이익    당기순이익         자산
A005930   2628804.0     453829.0  553252.0  64473.0  48849.0  3574575.0
A005380    763658.0       4198.0  253194.0   8638.0   5527.0  1988508.0
A035420     65039.0      13568.0   17321.0   2215.0   1349.0   137660.0
A003550    190210.0       8187.0   15854.0   6077.0   5921.0   226349.0
A034730    521826.0      79788.0  237261.0  -9227.0  -8324.0  1351392.0


IFRS(연결)         부채         자본 영업활동으로인한현금흐름
A005930    910698.0  2663877.0     118299.0
A005380   1229242.0   759266.0       8220.0
A035420     63108.0    74552.0       2779.0
A003550     33548.0   192801.0       2507.0
A034730    837787.0   513605.0       9948.0

[5 rows x 28 columns]

In [45]:
# 재무비율 탭에 있느 데이터를 가져와서 똑같은 방법으로 정리해보자

def make_fr_dataframe(firm_code):
# firm_code = 'A005930'
    fr_url = 'https://comp.fnguide.com/SVO2/asp/SVD_FinanceRatio.asp?pGB=1&cID=&MenuYn=Y&ReportGB=D&NewMenuID=104&stkGb=701&gicode=' + firm_code
    fr_page = requests.get(fr_url)
    fr_tables = pd.read_html(fr_page.text)

    temp_df = fr_tables[0]
    temp_df = temp_df.set_index(temp_df.columns[0])

# (현재 책)책 내용과 현재 url에 있는 구성이 다름
#     temp_df = temp_df.loc[['유동비율(유동자산 / 유동부채) * 100 유동비율계산에 참여한 계정 펼치기',
#                            '부채비율(총부채 / 총자본) * 100 부채비율계산에 참여한 계정 펼치기',
#                            '영업이익률(영업이익 / 영업수익) * 100 영업이익률계산에 참여한 계정 펼치기',
#                            'ROA(당기순이익(연율화) / 총자산(평균)) * 100 ROA계산에 참여한 계정 펼치기',
#                            'ROIC(세후영업이익(연율화)/영업투하자본(평균))*100 ROIC계산에 참여한 계정 펼치기']]

    temp_df = temp_df.loc[['유동비율계산에 참여한 계정 펼치기',
                           '부채비율계산에 참여한 계정 펼치기',
                           '영업이익률계산에 참여한 계정 펼치기',
                           'ROA계산에 참여한 계정 펼치기',
                           'ROIC계산에 참여한 계정 펼치기']]

    temp_df.index = ['유동비율', '부채비율', '영업이익률', 'ROA', 'ROIC']
    return temp_df
temp_df

            2017/12                                                      \
IFRS(연결)        매출액      영업이익     당기순이익         자산        부채         자본
A005930   2395754.0  536450.0  421867.0  3017521.0  872607.0  2144914.0


IFRS(연결) 영업활동으로인한현금흐름
A005930      621620.0

In [46]:
# 5개 회사 재무비율 데이터를 합쳐보기
firmcode_list = ['A005930', 'A005380', 'A035420', 'A003550', 'A034730']

for num, code in enumerate(firmcode_list):
    fr_df = make_fr_dataframe(code)
    fr_df_changed = change_df(code, fr_df)
    if num == 0:
        total_fr = fr_df_changed
    else:
        total_fr = pd.concat([total_fr, fr_df_changed])
total_fr

        2016/12                           2017/12                            \
           유동비율   부채비율 영업이익률   ROA   ROIC    유동비율   부채비율 영업이익률   ROA   ROIC
A005930   258.5   35.9  14.5   9.0   20.3   218.8   40.7  22.4  15.0   33.2
A005380   109.1  147.2   5.6   3.3    4.4   112.2  138.4   4.8   2.6    4.8
A035420   232.8   54.3  27.4  14.1  199.2   207.8   51.2  25.2  10.7  144.9
A003550   130.7   37.1  13.7   5.8   39.5   136.1   33.8  18.5  11.8   87.7
A034730   113.0  143.5   6.4   2.8    7.8   112.2  139.9   6.3   4.8    8.4

         ... 2019/12                         2020/03
         ...    유동비율   부채비율 영업이익률  ROA  ROIC    유동비율   부채비율 영업이익률   ROA   ROIC
A005930  ...   284.4   34.1  12.1  6.3  13.2   288.3   34.2  11.7   5.5   12.0
A005380  ...    86.1  154.7   3.4  1.7   2.6    85.2  161.9   3.4   1.1    2.4
A035420  ...   149.6   89.1  10.8  3.6  36.6   159.5   84.7  12.8   4.1   42.5
A003550  ...   175.5   18.0  15.6  4.9  41.8   173.4   17.4  38.3  10.5  149.0
A034730  ...   112.6  153.0   4.0  1.3   4.3   105.3  163.1  -3.9  -2.5   -4.4

[5 rows x 25 columns]

In [47]:
# 투자지표 탭에 있는 데이터 가져오기

def make_invest_dataframe(firm_code):
    invest_url = 'https://comp.fnguide.com/SVO2/asp/SVD_Invest.asp?pGB=1&cID=&MenuYn=Y&ReportGB=D&NewMenuID=105&stkGb=701&gicode=' + firm_code
    invest_page = requests.get(invest_url)
    invest_tables = pd.read_html(invest_page.text)
    temp_df = invest_tables[1]
    
    temp_df = temp_df.set_index(temp_df.columns[0])
    temp_df = temp_df.loc[['PER계산에 참여한 계정 펼치기',
                           'PCR계산에 참여한 계정 펼치기',
                           'PSR계산에 참여한 계정 펼치기',
                           'PBR계산에 참여한 계정 펼치기',
                           '총현금흐름']]
    temp_df.index = ['PER', 'PCR', 'PSR', 'PBR', '총현금흐름']
    return temp_df

In [48]:
# 5개 회사 투자지표 데이터를 합쳐보기
firmcode_list = ['A005930', 'A005380', 'A035420', 'A003550', 'A034730']

for num, code in enumerate(firmcode_list):
    invest_df = make_invest_dataframe(code)
    invest_df_changed = change_df(code, invest_df)
    if num == 0:
        total_invest = invest_df_changed
    else:
        total_invest = pd.concat([total_invest, invest_df_changed])
total_invest

        2016/12                            2017/12                             \
            PER    PCR   PSR   PBR   총현금흐름     PER    PCR   PSR   PBR   총현금흐름
A005930   13.18   6.85  1.46  1.48  423491    9.40   6.12  1.62  1.76  623891
A005380    7.71   4.76  0.45  0.61   74241   11.04   5.89  0.46  0.63   82152
A035420   34.14  28.04  6.36  5.17    9136   37.16  29.33  6.14  4.84    9682
A003550    9.82   7.69  1.09  0.76   14278    6.68   6.03  1.35  1.00   21812
A034730   21.26   2.72  0.20  1.16   88583   11.97   2.74  0.22  1.38   96487

         ... 2019/12                            2020/03                  \
         ...     PER    PCR   PSR   PBR   총현금흐름     PER  PCR  PSR   PBR
A005930  ...   17.63   7.42  1.65  1.49  494337     NaN  NaN  NaN  1.25
A005380  ...   11.20   4.90  0.32  0.47   65904     NaN  NaN  NaN  0.35
A035420  ...   52.72  28.43  4.66  4.27    8261     NaN  NaN  NaN  3.49
A003550  ...   12.02  10.33  1.97  0.69    9937     NaN  NaN  NaN  0.54
A034730  ...   25.91   2.26  0.19  1.00   99334     NaN  NaN  NaN  0.63


          총현금흐름
A005930  120668
A005380   16682
A035420    1177
A003550    6269
A034730   12325

[5 rows x 25 columns]

## 3.4 전 종목 코드 구해오기

In [51]:
path = r'C:\\work\\hun\\python_quant\\data\\data.xls' # KRX 에서 전체 종목 다운로드
code_data = pd.read_excel(path)
code_data = code_data[['종목코드', '기업명']]
code_data

        종목코드     기업명
0      60310      3S
1      95570  AJ네트웍스
2       6840   AK홀딩스
3      54620  APS홀딩스
4     265520   AP시스템
...      ...     ...
2351  189980  흥국에프엔비
2352     540    흥국화재
2353    3280    흥아해운
2354   37440      희림
2355  238490      힘스

[2356 rows x 2 columns]

In [52]:
# 종목코드 칼럼 개선
def make_code(x):
    x = str(x)
    return 'A'+'0'*(6-len(x))+x

code_data['종목코드'] = code_data['종목코드'].apply(make_code)
code_data # 실행할때마다 A 가 앞에 붙음..

         종목코드     기업명
0     A060310      3S
1     A095570  AJ네트웍스
2     A006840   AK홀딩스
3     A054620  APS홀딩스
4     A265520   AP시스템
...       ...     ...
2351  A189980  흥국에프엔비
2352  A000540    흥국화재
2353  A003280    흥아해운
2354  A037440      희림
2355  A238490      힘스

[2356 rows x 2 columns]

## 3.5 전 종목 재무데이터 가져오기

In [53]:
# 모든 종목에 대한 재무데이터 가져오기

import time

for num, code in enumerate(code_data['종목코드']):
    try:
        print(num, code)
        time.sleep(1)
        try:
            fs_df = make_fs_dataframe(code)
        except requests.exceptions.Timeout:
            time.sleep(60)
            fs_df = make_fs_dataframe(code)
        fs_df_changed = change_df(code, fs_df)
        if num == 0:
            total_fs = fs_df_changed
        else:
            total_fs = pd.concat([total_fs, fs_df_changed])
    except ValueError:
        continue
    except KeyError:
        continue

# total_fs # 결산일이 12월, 3월로 다른 기업들이 있어서 데이터가 NaN으로 표기될 수 있음
total_fs[['2017/12', '2018/12', '2019/12', '2020/03']] # 날짜 데이터만 가져옴

0 A060310
1 A095570
2 A006840
3 A054620
4 A265520
5 A211270
6 A027410
7 A282330

KeyboardInterrupt:

In [54]:
# 재무데이터를 엑셀로 저장
total_fs.to_excel(r'재무데이터.xlsx')

In [55]:
# 모든 종목 재무비율 데이터 합치고 엑셀에 저장

for num, code in enumerate(code_data['종목코드']):
    try:
        print(num, code)
        time.sleep(1)
        try:
            fr_df = make_fr_dataframe(code)
        except requests.exceptions.Timeout:
            time.sleep(60)
            fr_df = make_fr_dataframe(code)
        fr_df_changed = change_df(code, fr_df)
        if num == 0 :
            total_fr = fr_df_changed
        else:
            total_fr = pd.concat([total_fr, fr_df_changed])
    except ValueError:
        continue
    except KeyError:
        continue
        
total_fr.to_excel(r'재무비율데이터.xlsx')

0 A060310
1 A095570
2 A006840
3 A054620
4 A265520
5 A211270
6 A027410
7 A282330
8 A138930
9 A001460
10 A001040
11 A079160
12 A035760
13 A000120
14 A011150
15 A097950
16 A051500

KeyboardInterrupt:

In [27]:
# 모든 종목 투자지표 데이터 합치고 엑셀에 저장

for num, code in enumerate(code_data['종목코드'][313:]):
    try:
        print(num, code)
        time.sleep(1)
        try:
            invest_df = make_invest_dataframe(code)
        except requests.exceptions.Timeout:
            time.sleep(60)
            invest_df = make_invest_dataframe(code)
        invest_df_changed = change_df(code, invest_df)
        if num == 0 :
            total_invest = invest_df_changed
        else:
            total_invest = pd.concat([total_invest, invest_df_changed])
    except ValueError:
        continue
    except KeyError:
        continue
        
total_invest.to_excel(r'투자지표데이터.xlsx')

0 A086220
1 A033640
2 A087730
3 A005720
4 A002350
5 A089140
6 A065170
7 A139670
8 A003580
9 A137940
10 A041140
11 A217270
12 A225570
13 A251270
14 A104620
15 A090350
16 A000320
17 A194700
18 A285490
19 A229500
20 A006280
21 A144510
22 A031390
23 A142280
24 A005250
25 A065560
26 A004370
27 A072710
28 A054050
29 A040160
30 A069140
31 A126870
32 A060260
33 A012340
34 A270870
35 A222040
36 A144960
37 A900100
38 A085670
39 A119860
40 A064260
41 A093640
42 A039560
43 A058730
44 A023590
45 A032190
46 A068240
47 A086080
48 A271850
49 A019680
50 A006370
51 A008060
52 A178600
53 A000490
54 A020400
55 A008830
56 A048470
57 A008110
58 A004780
59 A005750
60 A000210
61 A004440
62 A017650
63 A006570
64 A007720
65 A290670
66 A078140
67 A001680
68 A084690
69 A036480
70 A128820
71 A117580
72 A025440
73 A027830
74 A104040
75 A016710
76 A262830
77 A303030
78 A307750
79 A020180
80 A003540
81 A045390
82 A009190
83 A108380
84 A006580
85 A014160
86 A047040
87 A009320
88 A042660
89 A003090
90 A069620
91 A007680
92 A000430
93 A311840
94 A048910
95 A005710
96 A006340
97 A003220
98 A024890
99 A290380
100 A002880
101 A290120
102 A071460
103 A000300
104 A120240
105 A003310
106 A114920
107 A078600
108 A065690
109 A012800
110 A015230
111 A096350
112 A140520
113 A131220
114 A010170
115 A054670
116 A001070
117 A023910
118 A006650
119 A001440
120 A084010
121 A001790
122 A001130
123 A003490
124 A005880
125 A003830
126 A016090
127 A069460
128 A021040
129 A067080
130 A192080
131 A035290
132 A012510
133 A302920
134 A213420
135 A077360
136 A004830
137 A090410
138 A024900
139 A263600
140 A194480
141 A263800
142 A199150
143 A139050
144 A017680
145 A206560
146 A145720
147 A067990
148 A002150
149 A006620
150 A100130
151 A005160
152 A001620
153 A075970
154 A001230
155 A086450
156 A023450
157 A004140
158 A099410
159 A007590
160 A005960
161 A281740
162 A016380
163 A083370
164 A083380
165 A026960
166 A002210
167 A102260
168 A033500
169 A005190
170 A025950
171 A000640
172 A170900
173 A088130
174 A028100
175 A282690
176 A041930
177 A001520
178 A084670
179 A030790
180 A002900
181 A082640
182 A060380
183 A079960
184 A008970
185 A228340
186 A092780
187 A104460
188 A088910
189 A094170
190 A049770
191 A013120
192 A018500
193 A006040
194 A030720
195 A014820
196 A163560
197 A109860
198 A032960
199 A001530
200 A004890
201 A002690
202 A023790
203 A005290
204 A025900
205 A000020
206 A000150
207 A011160
208 A241560
209 A042670
210 A034020
211 A016740
212 A078590
213 A270020
214 A073190
215 A176750
216 A030350
217 A203650
218 A220110
219 A217620
220 A187870
221 A066670
222 A024090
223 A003160
224 A092200
225 A110990
226 A263690
227 A214680
228 A263720
229 A109740
230 A033430
231 A090710
232 A131030
233 A196490
234 A066900
235 A127120
236 A092070
237 A101000
238 A134580
239 A039840
240 A013570
241 A210540
242 A079810
243 A227100
244 A113810
245 A043360
246 A197140
247 A106520
248 A068930
249 A033130
250 A033310
251 A105740
252 A263020
253 A290550
254 A007340
255 A187220
256 A026890
257 A163430
258 A131180
259 A042510
260 A232680
261 A050120
262 A171120
263 A069540
264 A285770
265 A115390
266 A200350
267 A171010
268 A084650
269 A217500
270 A092590
271 A141080
272 A060300
273 A038390
274 A228850
275 A238120
276 A215100
277 A090360
278 A238500
279 A108490
280 A900260
281 A067730
282 A071280
283 A032350
284 A000400
285 A023530
286 A004000
287 A286940
288 A280360
289 A004990
290 A005300
291 A011170
292 A002270
293 A071840
294 A038060
295 A082800
296 A162120
297 A085370
298 A060240
299 A058470
300 A039980
301 A016100
302 A197210
303 A012700
304 A302550
305 A131100
306 A277070
307 A042500
308 A219420
309 A027740
310 A098120
311 A227950
312 A147760
313 A035480
314 A038290
315 A204320
316 A001080
317 A267980
318 A005990
319 A127160
320 A093520
321 A141070
322 A088980
323 A094800
324 A100590
325 A067280
326 A072870
327 A215200
328 A133750
329 A200580
330 A041920
331 A233250
332 A236340
333 A086900
334 A015540
335 A078160
336 A065650
337 A138040
338 A008560
339 A000060
340 A021880
341 A140410
342 A241770
343 A090370
344 A059210
345 A058110
346 A096640
347 A017180
348 A257370
349 A267060
350 A012690
351 A005360
352 A149940
353 A080420
354 A080160
355 A204210
356 A100030
357 A087260
358 A101330
359 A250060
360 A033200
361 A009680
362 A118990
363 A006920
364 A009580
365 A001810
366 A009200
367 A033920
368 A008420
369 A279600
370 A028040
371 A095500
372 A025560
373 A218150
374 A007120
375 A006800
376 A265480
377 A310200
378 A085620
379 A239340
380 A049950
381 A213090
382 A207760
383 A225850
384 A002840
385 A268280
386 A107590
387 A134380
388 A003650
389 A059090
390 A214610
391 A201490
392 A214180
393 A155900
394 A206640
395 A018700
396 A035620
397 A064520
398 A029480
399 A053030
400 A084990
401 A064550
402 A208710
403 A142760
404 A065940
405 A086820
406 A038460
407 A281310
408 A044480
409 A216400
410 A086040
411 A199290
412 A032980
413 A222160
414 A043150
415 A003610
416 A267790
417 A001340
418 A014580
419 A046310
420 A035150
421 A036620
422 A066410
423 A002410
424 A177350
425 A299910
426 A096300
427 A007210
428 A225530
429 A250000
430 A002760
431 A014100
432 A003850
433 A006910
434 A000890
435 A226340
436 A206950
437 A003000
438 A001270
439 A026940
440 A014470
441 A015350
442 A011390
443 A005030
444 A008470
445 A100120
446 A066980
447 A064480
448 A251630
449 A033560
450 A126340
451 A121800
452 A148140
453 A100220
454 A200780
455 A141000
456 A090460
457 A083650
458 A215050
459 A271780
460 A086670
461 A138580
462 A082920
463 A054220
464 A042370
465 A032850
466 A148780
467 A238200
468 A093190
469 A065450
470 A210120
471 A005180
472 A072950
473 A143240
474 A003960
475 A008040
476 A007160
477 A014710
478 A006090
479 A079660
480 A100090
481 A005090
482 A122350
483 A014970
484 A018310
485 A053700
486 A009620
487 A023600
488 A111870
489 A001470
490 A006400
491 A006660
492 A309930
493 A028260
494 A207940
495 A032830
496 A291230
497 A018260
498 A028050
499 A009150
500 A005930
501 A001360
502 A010140
503 A016360
504 A068290
505 A029780
506 A000810
507 A006110
508 A009300
509 A145990
510 A003230
511 A225190
512 A002170
513 A272550
514 A000070
515 A002810
516 A054540
517 A065570
518 A005680
519 A003720
520 A082660
521 A023000
522 A073640
523 A004380
524 A002450
525 A032280
526 A002290
527 A000520
528 A009770
529 A037460
530 A032750
531 A054090
532 A005500
533 A000250
534 A004690
535 A024950
536 A038500
537 A017480
538 A001880
539 A010960
540 A046390
541 A004450
542 A009470
543 A011230
544 A001820
545 A000390
546 A027580
547 A038540
548 A041650
549 A091580
550 A263810
551 A089980
552 A042940
553 A042600
554 A075180
555 A263540
556 A007540
557 A248170
558 A038070
559 A006730
560 A079650
561 A100660
562 A007860
563 A200880
564 A012860
565 A019770
566 A017390
567 A043710
568 A046890
569 A004410
570 A063170
571 A027040
572 A018680
573 A021050
574 A093920
575 A189860
576 A178320
577 A122690
578 A140070
579 A011370
580 A065710
581 A008490
582 A035890
583 A003100
584 A123420
585 A007610
586 A067370
587 A171090
588 A136490
589 A002820
590 A014620
591 A037350
592 A014910
593 A003080
594 A004980
595 A011300
596 A081580
597 A045300
598 A015750
599 A000180
600 A080470
601 A043260
602 A002420
603 A053060
604 A017510
605 A214310
606 A004360
607 A004490
608 A011560
609 A001430
610 A306200
611 A003030
612 A019440
613 A058650
614 A013000
615 A100700
616 A234100
617 A024830
618 A091090
619 A021820
620 A067830
621 A033530
622 A135270
623 A258830
624 A036630
625 A039310
626 A075580
627 A067770
628 A053450
629 A027970
630 A145210
631 A252500
632 A049180
633 A268600
634 A108860
635 A208370
636 A258250
637 A068270
638 A068760
639 A091990
640 A053110
641 A032680
642 A210610
643 A066910
644 A043100
645 A154040
646 A035610
647 A036830
648 A230980
649 A004430
650 A086980
651 A050960
652 A017550
653 A084180
654 A253840
655 A185190
656 A058530
657 A236200
658 A094840
659 A192440
660 A099440
661 A033790
662 A159910
663 A115570
664 A258540
665 A008800
666 A253450
667 A245030
668 A013810
669 A049830
670 A020710
671 A033170
672 A260870
673 A048870
674 A025320
675 A134790
676 A269620
677 A131090
678 A232830
679 A016590
680 A029530
681 A004970
682 A001000
683 A025870
684 A215600
685 A065350
686 A011930
687 A005390
688 A004170
689 A035510
690 A034300
691 A031430

692 A031440
693 A006880
694 A056000
695 A002800
696 A307180
697 A005800
698 A001720
699 A009270
700 A017000
701 A002700
702 A012790
703 A138070
704 A019170
705 A002870
706 A005450
707 A293940
708 A257730
709 A277480
710 A055550
711 A001770
712 A056700
713 A187270
714 A004080
715 A243840
716 A108320
717 A222800
718 A036710
719 A160980
720 A217330
721 A102280
722 A003410
723 A003620
724 A010280
725 A004770
726 A217320
727 A122800
728 A208640
729 A222420
730 A037760
731 A136510
732 A099320
733 A049960
734 A050890
735 A066790
736 A222080
737 A004920
738 A236030
739 A103660
740 A245450
741 A264660
742 A112610
743 A115530
744 A225330
745 A115480
746 A189330
747 A096530
748 A900120
749 A101240
750 A047920
751 A189540
752 A060590
753 A036170
754 A260930
755 A013990
756 A123860
757 A025980
758 A008700
759 A058220
760 A090430
761 A002790
762 A052710
763 A074430
764 A092040
765 A083930
766 A149950
767 A036010
768 A002030
769 A183190
770 A002310
771 A050860
772 A246720
773 A067390
774 A127710
775 A267850
776 A020560
777 A154030
778 A227610
779 A143160
780 A054800
781 A060570
782 A122900
783 A099190
784 A214430
785 A040910
786 A068940
787 A052860
788 A010780
789 A069920
790 A038880
791 A003560
792 A122050
793 A101390
794 A226350
795 A078860
796 A114810
797 A031310
798 A185490
799 A059100
800 A149010
801 A175250
802 A052460
803 A119830
804 A124500
805 A223220
806 A027360
807 A033660
808 A032080
809 A013310
810 A059120
811 A023890
812 A101140
813 A067160
814 A001540
815 A053800
816 A251280
817 A065660
818 A271400
819 A001780
820 A260660
821 A002250
822 A131370
823 A140670
824 A096610
825 A061040
826 A148250
827 A196170
828 A123750
829 A085810
830 A117670
831 A267810
832 A018250
833 A161000
834 A196300
835 A205500
836 A052790
837 A131400
838 A290740
839 A238090
840 A092600
841 A266170
842 A174900
843 A255440
844 A030960
845 A102120
846 A224810
847 A041590
848 A019990
849 A011090
850 A208890
851 A041440
852 A270660
853 A038680
854 A217480
855 A121890
856 A030270
857 A097780
858 A073070
859 A042110
860 A065420
861 A270210
862 A103230
863 A260970
864 A900080
865 A101490
866 A095910
867 A275630
868 A031330
869 A060540
870 A158300
871 A112240
872 A056190
873 A080000
874 A160600
875 A263920
876 A086460
877 A005850
878 A246250
879 A041510
880 A299670
881 A007820
882 A109610
883 A012750
884 A123700
885 A025530
886 A080440
887 A217910
888 A224020
889 A096630
890 A069510
891 A041910
892 A234300
893 A039440
894 A098660
895 A052020
896 A237690
897 A050760
898 A288620
899 A058610
900 A043340
901 A023960
902 A298690
903 A054630
904 A200710
905 A140910
906 A078520
907 A298380
908 A203400
909 A003800
910 A088800
911 A138360
912 A039230
913 A050320
914 A015260
915 A234070
916 A072990
917 A044990
918 A176440
919 A028300
920 A067630
921 A043220
922 A239610
923 A044780
924 A033600
925 A071670
926 A045660
927 A224110
928 A021080
929 A089530
930 A182400
931 A207490
932 A109960
933 A007460
934 A003060
935 A089970
936 A214870
937 A230240
938 A064510
939 A230360
940 A038870
941 A128540
942 A086520
943 A038110
944 A073540
945 A064850
946 A064090
947 A036810
948 A173940
949 A083500
950 A065160
951 A054940
952 A950130
953 A205100
954 A092870
955 A067570
956 A140610
957 A101400
958 A036570
959 A217820
960 A138250
961 A031860
962 A224760
963 A256630
964 A256840
965 A273060
966 A310840
967 A208860
968 A183490
969 A085310
970 A262760
971 A009810
972 A206400
973 A069410
974 A004250
975 A048830
976 A096870
977 A276240
978 A900140
979 A061970
980 A138690
981 A290650
982 A066970
983 A156100
984 A311060
985 A073110
986 A083310
987 A037950
988 A170920
989 A183350
990 A058630
991 A058970
992 A019590
993 A097520
994 A179290
995 A225860
996 A009780
997 A123040
998 A251960
999 A032790
1000 A033160
1001 A204020
1002 A259630
1003 A115960
1004 A090740
1005 A014440
1006 A007530
1007 A143540
1008 A111770
1009 A009970
1010 A036180
1011 A003520
1012 A000670
1013 A036560
1014 A006740
1015 A242850
1016 A012280
1017 A265560
1018 A012160
1019 A036000
1020 A053280
1021 A015360
1022 A122640
1023 A179720
1024 A900300
1025 A045060
1026 A080520
1027 A007310
1028 A079440
1029 A039830
1030 A046120
1031 A014940
1032 A002630
1033 A065500
1034 A271560
1035 A001800
1036 A010470
1037 A053980
1038 A052420
1039 A241790
1040 A039200
1041 A226400
1042 A031510
1043 A048260
1044 A138080
1045 A080580
1046 A067170
1047 A173130
1048 A049480
1049 A226950
1050 A057540
1051 A057680
1052 A123010
1053 A082210
1054 A109080
1055 A153710
1056 A052770
1057 A057030
1058 A122990
1059 A232140
1060 A067900
1061 A155650
1062 A251370
1063 A066430
1064 A193250
1065 A019210
1066 A122870
1067 A079000
1068 A070960
1069 A114630
1070 A316140
1071 A032820
1072 A041190
1073 A115440
1074 A004720
1075 A118000
1076 A046970
1077 A215360
1078 A072470
1079 A073560
1080 A153490
1081 A082850
1082 A037400
1083 A010050
1084 A101170
1085 A006980
1086 A066590
1087 A017370
1088 A046940
1089 A215380
1090 A065680
1091 A105840
1092 A018620
1093 A010400
1094 A049800
1095 A016880
1096 A095720
1097 A103130
1098 A005820
1099 A032940
1100 A240810
1101 A074600
1102 A104830
1103 A014190
1104 A123100
1105 A030530
1106 A012620
1107 A216280
1108 A008370
1109 A008290
1110 A101160
1111 A095270
1112 A010600
1113 A065950
1114 A114190
1115 A076080
1116 A196700
1117 A069080
1118 A053580
1119 A044340
1120 A112040
1121 A065370
1122 A140660
1123 A038620
1124 A299900
1125 A036090
1126 A136540
1127 A097800
1128 A192390
1129 A008600
1130 A900340
1131 A033270
1132 A014830
1133 A036200
1134 A018000
1135 A000910
1136 A047400
1137 A203450
1138 A011330
1139 A077500
1140 A011320
1141 A086390
1142 A241690
1143 A142210
1144 A121060
1145 A048430
1146 A206650
1147 A089850
1148 A084440
1149 A032620
1150 A264450
1151 A078070
1152 A002920
1153 A024800
1154 A000700
1155 A054930
1156 A252370
1157 A069330
1158 A049520
1159 A287410
1160 A003470
1161 A056090
1162 A011690
1163 A263770
1164 A072130
1165 A000220
1166 A195990
1167 A023410
1168 A056080
1169 A001200
1170 A084370
1171 A178780
1172 A221800
1173 A179900
1174 A263050
1175 A000100
1176 A003460
1177 A191410
1178 A008730
1179 A008250
1180 A039020
1181 A025820
1182 A060230
1183 A067920
1184 A044960
1185 A302430
1186 A214320
1187 A073490
1188 A215790
1189 A246960
1190 A088390
1191 A272290
1192 A053350
1193 A258610
1194 A033110
1195 A041520
1196 A054210
1197 A065440
1198 A088260
1199 A139480
1200 A036260
1201 A115610
1202 A078020
1203 A208850
1204 A080010
1205 A086890
1206 A007660
1207 A005950
1208 A015020
1209 A047560
1210 A900110
1211 A067010
1212 A093230
1213 A223310
1214 A241510
1215 A052190
1216 A226360
1217 A101360
1218 A102710
1219 A094190
1220 A063760
1221 A123570
1222 A095190
1223 A091120
1224 A232530
1225 A102460
1226 A039030
1227 A088290
1228 A084680
1229 A181340
1230 A035810
1231 A090850
1232 A092130
1233 A016250
1234 A096040
1235 A134060
1236 A001840
1237 A000760
1238 A024810
1239 A014990
1240 A041830
1241 A079950
1242 A277410
1243 A060150
1244 A033230
1245 A006490
1246 A037330
1247 A023800
1248 A034590
1249 A211050
1250 A083640
1251 A216050
1252 A049070
1253 A119610
1254 A158310
1255 A017250
1256 A129260
1257 A240340
1258 A108790
1259 A035080
1260 A051370
1261 A064290
1262 A189300
1263 A150840
1264 A048530
1265 A023810
1266 A175140
1267 A115310
1268 A039290
1269 A041020
1270 A247300
1271 A071200
1272 A101930
1273 A078940
1274 A249420
1275 A000230
1276 A013360
1277 A003120
1278 A068330
1279 A003200
1280 A007110
1281 A058450
1282 A007570
1283 A008500
1284 A019540
1285 A081000
1286 A020760
1287 A020150
1288 A103590
1289 A094820
1290 A015860
1291 A226320
1292 A950140
1293 A049550
1294 A230400
1295 A043910
1296 A234920
1297 A033240
1298 A174880
1299 A049630
1300 A000950
1301 A120780
1302 A110020
1303 A065530
1304 A208140
1305 A022220
1306 A040420
1307 A045510
1308 A065620
1309 A217190
1310 A095700
1311 A072520
1312 A122310
1313 A066830
1314 A187420
1315 A225220
1316 A123330
1317 A159580
1318 A147830
1319 A033100
1320 A019570
1321 A079370
1322 A054950
1323 A096690
1324 A090470
1325 A137950
1326 A033320
1327 A194370
1328 A026040
1329 A250300
1330 A126880
1331 A033050
1332 A094970
1333 A058420
1334 A025620
1335 A036420
1336 A089790
1337 A030000
1338 A052670
1339 A271980
1340 A001560
1341 A023440
1342 A038010
1343 A002620
1344 A080220
1345 A006220

1346 A089590
1347 A229000
1348 A082270
1349 A044060
1350 A004910
1351 A004700
1352 A001550
1353 A000480
1354 A120030
1355 A034940
1356 A101730
1357 A067000
1358 A018470
1359 A002600
1360 A185750
1361 A063160
1362 A001630
1363 A033340
1364 A221670
1365 A036930
1366 A044380
1367 A229480
1368 A051980
1369 A072020
1370 A000440
1371 A054180
1372 A228760
1373 A314130
1374 A043610
1375 A263860
1376 A208350
1377 A114570
1378 A299480
1379 A051160
1380 A053050
1381 A119850
1382 A065060
1383 A204840
1384 A013870
1385 A018290
1386 A071320
1387 A135160
1388 A111820
1389 A010580
1390 A035000
1391 A106080
1392 A115450
1393 A219750
1394 A088790
1395 A018120
1396 A109820
1397 A086060
1398 A036890
1399 A003780
1400 A007370
1401 A010640
1402 A100250
1403 A051630
1404 A272450
1405 A011000
1406 A002780
1407 A233990
1408 A085660
1409 A900040
1410 A009310
1411 A094850
1412 A004650
1413 A278280
1414 A000650
1415 A140290
1416 A096240
1417 A013720
1418 A012600
1419 A066360
1420 A033250
1421 A047820
1422 A094360
1423 A016920
1424 A220250
1425 A035720
1426 A042000
1427 A006380
1428 A071850
1429 A180400
1430 A050110
1431 A109070
1432 A900310
1433 A078340
1434 A205290
1435 A263700
1436 A214370
1437 A221980
1438 A043290
1439 A250930
1440 A258790
1441 A192250
1442 A029460
1443 A002380
1444 A115500
1445 A281820
1446 A089150
1447 A009070
1448 A025880
1449 A093320
1450 A073010
1451 A105330
1452 A039420
1453 A083550
1454 A032500
1455 A225430
1456 A145270
1457 A030200
1458 A058860
1459 A053210
1460 A033780
1461 A064820
1462 A256940
1463 A024880
1464 A042040
1465 A054410
1466 A217600
1467 A089010
1468 A220260
1469 A052400
1470 A094860
1471 A046070
1472 A047770
1473 A080530
1474 A224060
1475 A078650
1476 A104540
1477 A027050
1478 A007810
1479 A101670
1480 A123410
1481 A152330
1482 A003690
1483 A036690
1484 A049430
1485 A183300
1486 A041960
1487 A089890
1488 A009730
1489 A189350
1490 A192820
1491 A044820
1492 A241710
1493 A005070
1494 A005420
1495 A069110
1496 A071950
1497 A166480
1498 A045970
1499 A029960
1500 A002020
1501 A003070
1502 A144620
1503 A102940
1504 A120110
1505 A950160
1506 A138490
1507 A021240
1508 A033290
1509 A056360
1510 A121850
1511 A015710
1512 A052330
1513 A126600
1514 A200130
1515 A031820
1516 A225650
1517 A192400
1518 A284740
1519 A060280
1520 A015590
1521 A040350
1522 A051780
1523 A115180
1524 A182360
1525 A066310
1526 A136660
1527 A016600
1528 A264900
1529 A005740
1530 A215570
1531 A043590
1532 A114120
1533 A110790
1534 A083790
1535 A900250
1536 A045520
1537 A214150
1538 A237880
1539 A020120
1540 A311270
1541 A039490
1542 A012170
1543 A054780
1544 A219130
1545 A180060
1546 A065130
1547 A015890
1548 A006890
1549 A023160
1550 A003240
1551 A011280
1552 A053620
1553 A004100
1554 A116100
1555 A009410
1556 A044490
1557 A001420
1558 A007980
1559 A191420
1560 A182690
1561 A066700
1562 A095610
1563 A131970
1564 A055490
1565 A308700
1566 A089030
1567 A258050
1568 A054450
1569 A091440
1570 A196450
1571 A078000
1572 A200230
1573 A214420
1574 A215480
1575 A051360
1576 A045340
1577 A057880
1578 A108230
1579 A079970
1580 A199800
1581 A140890
1582 A105550
1583 A026150
1584 A117730
1585 A033830
1586 A084870
1587 A228180
1588 A064760
1589 A246710
1590 A277880
1591 A131290
1592 A246690
1593 A019180
1594 A062860
1595 A091810
1596 A004870
1597 A191600
1598 A104480
1599 A081150
1600 A130740
1601 A217880
1602 A084730
1603 A046210
1604 A034230
1605 A033540
1606 A043200
1607 A217950
1608 A214450
1609 A208340
1610 A005690
1611 A177830
1612 A037070
1613 A150900
1614 A037030
1615 A047310
1616 A266870
1617 A170790
1618 A049120
1619 A038950
1620 A278990
1621 A106240
1622 A131760
1623 A140860
1624 A091700
1625 A194510
1626 A038160
1627 A202960
1628 A032800
1629 A043090
1630 A036580
1631 A027710
1632 A225590
1633 A054300
1634 A068050
1635 A028670
1636 A222110
1637 A010820
1638 A016800
1639 A060900
1640 A263750
1641 A001020
1642 A087010
1643 A090080
1644 A043370
1645 A010770
1646 A227420
1647 A119500
1648 A016670
1649 A056730
1650 A005490
1651 A022100
1652 A058430
1653 A047050
1654 A009520
1655 A003670
1656 A189690
1657 A176560
1658 A141020
1659 A007630
1660 A290720
1661 A005670
1662 A094940
1663 A007330
1664 A017810
1665 A093380
1666 A023900
1667 A103140
1668 A005810
1669 A195440
1670 A214270
1671 A220100
1672 A035200
1673 A203690
1674 A303360
1675 A053610
1676 A053160
1677 A075130
1678 A222670
1679 A023770
1680 A150440
1681 A032580
1682 A051380
1683 A241820
1684 A237750
1685 A131390
1686 A054340
1687 A024850
1688 A031980
1689 A002230
1690 A242350
1691 A239890
1692 A137400
1693 A128660
1694 A006140
1695 A087600
1696 A033180
1697 A064800
1698 A161580
1699 A270520
1700 A284620
1701 A261200
1702 A086790
1703 A099340
1704 A099350
1705 A067310
1706 A307160
1707 A166090
1708 A293480
1709 A039130
1710 A136480
1711 A003380
1712 A172580
1713 A153360
1714 A159650
1715 A149980
1716 A013030
1717 A126700
1718 A200470
1719 A071090
1720 A221840
1721 A106190
1722 A019490
1723 A000080
1724 A000140
1725 A066130
1726 A152550
1727 A004590
1728 A036460
1729 A039340
1730 A005430
1731 A071050
1732 A034950
1733 A010040
1734 A025540
1735 A222980
1736 A226610
1737 A004090
1738 A025550
1739 A002200
1740 A002960
1741 A017890
1742 A080720
1743 A123890
1744 A015760
1745 A063570
1746 A041460
1747 A006200
1748 A101680
1749 A039740
1750 A053300
1751 A025770
1752 A271740
1753 A281410
1754 A291210
1755 A310870
1756 A002300
1757 A023350
1758 A025890
1759 A000970
1760 A104700
1761 A017960
1762 A023760
1763 A054040
1764 A050540
1765 A161890
1766 A024720
1767 A021650
1768 A161390
1769 A000240
1770 A053590
1771 A034830
1772 A007280
1773 A168490
1774 A037230
1775 A010100
1776 A047810
1777 A123690
1778 A003350
1779 A030520
1780 A052600
1781 A011500
1782 A002390
1783 A014790
1784 A092460
1785 A060980
1786 A222810
1787 A039670
1788 A053690
1789 A042700
1790 A008930
1791 A128940
1792 A047080
1793 A009240
1794 A020000
1795 A003680
1796 A105630
1797 A069640
1798 A016450
1799 A009180
1800 A070300
1801 A221610
1802 A070590
1803 A213500
1804 A014680
1805 A004710
1806 A010420
1807 A004150
1808 A025750
1809 A226440
1810 A042520
1811 A004960
1812 A011700
1813 A078350
1814 A045100
1815 A001750
1816 A018880
1817 A009420
1818 A014130
1819 A046110
1820 A024740
1821 A005860
1822 A300720
1823 A123840
1824 A002220
1825 A006390
1826 A003300
1827 A007770
1828 A051600
1829 A052690
1830 A130660
1831 A107640
1832 A002320
1833 A097230
1834 A003480
1835 A180640
1836 A005110
1837 A079170
1838 A009460
1839 A086960
1840 A054920
1841 A215090
1842 A077280
1843 A002680
1844 A066110
1845 A000880
1846 A027390
1847 A088350
1848 A000370
1849 A265920
1850 A012450
1851 A264290
1852 A279410
1853 A009830
1854 A003530
1855 A102210
1856 A220630
1857 A195870
1858 A034810
1859 A076610
1860 A101530
1861 A220180
1862 A143210
1863 A900270
1864 A000720
1865 A267270
1866 A170030
1867 A005440
1868 A086280
1869 A064350
1870 A079430
1871 A012330
1872 A010620
1873 A048410
1874 A069960
1875 A004560
1876 A016790
1877 A011200
1878 A004310
1879 A126560
1880 A017800
1881 A011210
1882 A267260
1883 A005380
1884 A026180
1885 A004020
1886 A011760
1887 A009540
1888 A267250
1889 A001500
1890 A227840
1891 A039010
1892 A001450
1893 A057050
1894 A204990
1895 A092300
1896 A053660
1897 A011080
1898 A093240
1899 A003010
1900 A111110
1901 A008770
1902 A060560
1903 A064240
1904 A039610
1905 A002460
1906 A013520
1907 A241590
1908 A006060
1909 A010690
1910 A126640
1911 A086250
1912 A204630
1913 A133820
1914 A061250
1915 A134780
1916 A010660
1917 A000850
1918 A123260
1919 A016580
1920 A032560
1921 A004800
1922 A094280
1923 A097870
1924 A298040
1925 A298050
1926 A298020
1927 A298000
1928 A093370
1929 A050090
1930 A081660
1931 A290270
1932 A005870
1933 A284420
1934 A205470
1935 A115160
1936 A028080
1937 A200670
1938 A212310
1939 A079980
1940 A065510
1941 A005010
1942 A243070
1943 A084110
1944 A145020
1945 A069260
1946 A024060
1947 A010240
1948 A189980
1949 A000540
1950 A003280
1951 A037440
1952 A238490

## 3.6 가격 데이터 가져오기

In [56]:
import requests
import bs4
import pandas as pd
import time

price_url = 'https://fchart.stock.naver.com/sise.nhn?symbol=005935&timeframe=day&count=1500&requestType=0'
price_data = requests.get(price_url)

price_data_bs = bs4.BeautifulSoup(price_data.text, 'lxml')
item_list = price_data_bs.find_all('item')
temp = item_list[0]['data']
temp.split('|') # 순서대로 날짜, 시가, 고가, 저가, 종가, 거래량

date_list = []
price_list = []
for item in item_list:
    temp_data = item['data']
    datas = temp_data.split('|')
    date_list.append(datas[0])
    price_list.append(datas[4])

price_df = pd.DataFrame({'종가' : price_list}, index=date_list) # 인덱스가 날짜, 칼럼이 종가
price_df

             종가
20140619  20720
20140620  20780
20140623  21180
20140624  21600
20140625  21420
...         ...
20200720  46950
20200721  47700
20200722  47250
20200723  47050
20200724  47150

[1500 rows x 1 columns]

In [57]:
# 가격을 naver차트로부터 가져와 dataframe 만드는 함수
# 칼럼명을 종가 -> 회사코드로 바꿈
def make_price_dataframe(code, timeframe, count):
    url = 'https://fchart.stock.naver.com/sise.nhn?requestType=0'
    price_url = url + '&symbol='+ code + '&timeframe=' + timeframe + '&count=' + count
    price_data = requests.get(price_url)
    price_data_bs = bs4.BeautifulSoup(price_data.text, 'lxml')
    item_list = price_data_bs.find_all('item')
    
    date_list = []
    price_list = []
    for item in item_list:
        temp_data = item['data']
        datas = temp_data.split('|')
        date_list.append(datas[0])
        price_list.append(datas[4])

    price_df = pd.DataFrame({code:price_list}, index=date_list)
    
    return price_df

In [58]:
make_price_dataframe('005380', 'day', '1500')

          005380
20140619  223500
20140620  218000
20140623  219500
20140624  224500
20140625  228500
...          ...
20200720  121500
20200721  121500
20200722  118500
20200723  124500
20200724  122500

[1500 rows x 1 columns]

In [59]:
# 5개 회사 날짜별로 종가 merge하기 (옆으로)
firmcode_list = ['005930', '005380', '035420', '003550', '034730']

for num, code in enumerate(firmcode_list):
    price_df = make_price_dataframe(code, 'day', '1500')
    if num == 0:
        total_price = price_df
    else:
        total_price = pd.merge(total_price, price_df, how='outer', right_index=True, left_index=True)

total_price

         005930  005380  035420 003550  034730
20140619  26460  223500  155621  63200  170500
20140620  26020  218000  157624  61800  172500
20140623  26440  219500  165435  61700  172500
20140624  26900  224500  165234  64300  171500
20140625  26400  228500  164634  63200  166000
...         ...     ...     ...    ...     ...
20200720  54200  121500  263000  71800  231000
20200721  55300  121500  270000  72200  233500
20200722  54700  118500  270000  73200  235500
20200723  54100  124500  284000  72600  230000
20200724  54200  122500  281000  72100  224500

[1500 rows x 5 columns]

In [61]:
# 거래소에서 가져온 회사코드 데이터의 'A'는 빼고 데이터프레임 만듬
path = r'C:\\work\\hun\\python_quant\\data\\data.xls'
code_data = pd.read_excel(path)
code_data = code_data[['종목코드', '기업명']]

def make_code2(x):
    x = str(x)
    return '0' * (6-len(x)) + x

code_data['종목코드'] = code_data['종목코드'].apply(make_code2)

In [62]:
# make_price_dataframe 함수를 이용해 가격 데이터를 다 가져와 데이터프레임 만듬
for num, code in enumerate(code_data['종목코드']):
    try:
        print(num, code)
        time.sleep(1)
        try:
            price_df = make_price_dataframe(code, 'day', '1500')
        except requests.exceptions.Timeout:
            time.sleep(60)
            price_df = make_price_dataframe(code, 'day', '1500')
        if num == 0 :
            total_price = price_df
        else:
            total_price = pd.merge(total_price, price_df, how='outer', right_index=True, left_index=True)
    except ValueError:
        continue
    except KeyError:
        continue

total_price
# 엑셀에 저장하기전 날짜 문자열을 판다스의 날짜 타입으로 변환
total_price.index = pd.to_datetime(total_price.index)
total_price.to_excel('가격데이터.xlsx')

0 060310
1 095570
2 006840
3 054620
4 265520
5 211270
6 027410
7 282330
8 138930
9 001460
10 001040
11 079160
12 035760
13 000120
14 011150
15 097950
16 051500
17 058820
18 023460
19 065770
20 083660
21 000590
22 012030
23 322780
24 016610
25 005830
26 000990
27 139130
28 068790
29 004840
30 241520
31 155660
32 069730

KeyboardInterrupt: